use_frameworks!

platform :ios, '9.0'

target 'SHBasicTools_Example' do
  pod 'SHBasicTools', :path => '../'

  target 'SHBasicTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
