use_frameworks!

platform :ios, '10.0'

#pod install 报错：The 'Pods-SHBasicTools_Example' target has transitive dependencies that include statically linked binaries
pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

target 'SHBasicTools_Example' do
  pod 'SHBasicTools', :path => '../'

  target 'SHBasicTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
